### ISSUE TITLE
Searching for staked Unicode symbols 

### ISSUE THREAD

**Issue by themadmax86** [decentraweb/decentrawebjs#7]
![Screenshot_2022-09-23-06-49-05-93_e4424258c8b8649f6e67d283a50a2cbc](https://user-images.githubusercontent.com/101009358/191943868-bcb577f4-2ea8-457e-8b97-689d722c5480.jpg)

When I paste my TLD x (Unicode) it shows me a red exclamation mark. It is not possible to register a sub domain using my mark. I paid for this mark, it was available and I staked it.. So please simplify its search for potential SLD buyers. Maybe you  could create filters, after expanding which the user can choose from, for example: numbers, Emoji's, Unicode & letters, special characters 3 digit TLDs etc. After selecting one of the filters, all the staked TLDs will be shown with the registration prices listed

**Comment by lytvynenkosv** [comment]
This repository is for Decentraweb SDK. This issue is not related to SDK.
